{
 "title": "covid",
 "description": "covid-19",
 "tags": [ "covid" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "country", "label": "country", "query": "show series from world" },
   { "name": "state", "label": "state", "query": "show series from world" }
  ]
 },
 "panels": [
  {
   "title": "Covid History for $country",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "world",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    },
    {
     "alias": "death",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "world",
     "select": [
      [
       { "params": [ "death" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    },
    {
     "alias": "recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "world",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "All Confirmed Cases",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Confirmed",
     "measurement": "world_todays",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Deaths",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Death",
     "measurement": "world_todays",
     "select": [
      [
       { "params": [ "death" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Recovered",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Recovered",
     "measurement": "world_todays",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "India's total death",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Recovered",
     "measurement": "india",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "India's today's death",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Recovered",
     "measurement": "india",
     "select": [
      [
       { "params": [ "todayDeaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "India's total cases",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Recovered",
     "measurement": "india",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "India's today's cases",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Recovered",
     "measurement": "india",
     "select": [
      [
       { "params": [ "todayCases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "India's total recovered",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Recovered",
     "measurement": "india",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "India's active cases",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Recovered",
     "measurement": "india",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "India's critical cases",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "alias": "Recovered",
     "measurement": "india",
     "select": [
      [
       { "params": [ "critical" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}